/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unesp.rc.demogsonutils;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import br.unesp.rc.modelo.Classe;
import br.unesp.rc.modelo.Atributo;
import br.unesp.rc.repositorio.ClasseRepositorio;
import br.unesp.rc.arquivoutils.ArquivoUtils;
import br.unesp.rc.gsonutils.utils.GsonUtils;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author luizh
 */
public class JFramePrincipal extends javax.swing.JFrame {

    List<Atributo> atributos = new ArrayList<>();

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        this.centralizaFrameToScreem();
        // this.setMetalLookAndFeel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtClasse = new javax.swing.JTextField();
        bntAdicionarClasse = new javax.swing.JButton();
        txtPacote = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbRelacionamentos = new javax.swing.JComboBox<>();
        txtRelacionamentos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbMultiplicidade = new javax.swing.JComboBox<>();
        txtMultiplicidade = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbModificadores = new javax.swing.JComboBox<>();
        btnAdicionarAtributo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTipoAtributo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNomeAtributo = new javax.swing.JTextField();
        btnNovaClasse = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnMostrarClasses = new javax.swing.JButton();
        bntSalvarProjeto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRespostaClasse = new javax.swing.JTextArea();
        btnSalvarUml = new javax.swing.JButton();
        btnSalvarEscolhido = new javax.swing.JButton();
        txtSalvar = new javax.swing.JTextField();
        btnAbrirProjeto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome da Classe");

        bntAdicionarClasse.setText("Selecionar Classe");
        bntAdicionarClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarClasseActionPerformed(evt);
            }
        });

        txtPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacoteActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome do Pacote");

        cbRelacionamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem Relacao", "Heranca", "Agregacao", "Composicao" }));
        cbRelacionamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRelacionamentosActionPerformed(evt);
            }
        });

        txtRelacionamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRelacionamentosActionPerformed(evt);
            }
        });

        jLabel2.setText("Classe a ser Relacionada");

        cbMultiplicidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem Relacao", "1:1", "1:1..*", "1:0..*", "*:*", "0..*:0..*", "1..*:1..*" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtClasse, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtPacote)
                            .addComponent(bntAdicionarClasse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRelacionamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMultiplicidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMultiplicidade, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtRelacionamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRelacionamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRelacionamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPacote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMultiplicidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMultiplicidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntAdicionarClasse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Modificador");

        cbModificadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "private", "public", "protected" }));
        cbModificadores.setEnabled(false);

        btnAdicionarAtributo.setText("Adicionar Atributo");
        btnAdicionarAtributo.setEnabled(false);
        btnAdicionarAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAtributoActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo");

        txtTipoAtributo.setEnabled(false);
        txtTipoAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoAtributoActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome");

        txtNomeAtributo.setEnabled(false);
        txtNomeAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAtributoActionPerformed(evt);
            }
        });

        btnNovaClasse.setText("Finalizar Classe");
        btnNovaClasse.setEnabled(false);
        btnNovaClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaClasseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovaClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(cbModificadores, 0, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtTipoAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnAdicionarAtributo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbModificadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionarAtributo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNovaClasse)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        btnMostrarClasses.setText("Mostrar UML");
        btnMostrarClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarClassesActionPerformed(evt);
            }
        });

        bntSalvarProjeto.setText("Salvar Projeto");
        bntSalvarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarProjetoActionPerformed(evt);
            }
        });

        txtRespostaClasse.setColumns(20);
        txtRespostaClasse.setRows(5);
        jScrollPane1.setViewportView(txtRespostaClasse);

        btnSalvarUml.setText("Salvar UML");
        btnSalvarUml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUmlActionPerformed(evt);
            }
        });

        btnSalvarEscolhido.setText("Salvar Escolhido");
        btnSalvarEscolhido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEscolhidoActionPerformed(evt);
            }
        });

        btnAbrirProjeto.setText("Abrir Projeto");
        btnAbrirProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirProjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMostrarClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvarUml, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalvarEscolhido, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(btnAbrirProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntSalvarProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarClasses)
                    .addComponent(btnSalvarUml)
                    .addComponent(txtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarEscolhido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAbrirProjeto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntSalvarProjeto)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntAdicionarClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarClasseActionPerformed
        bntAdicionarClasse.setEnabled(false);
        txtClasse.setEnabled(false);
        txtPacote.setEnabled(false);
        cbRelacionamentos.setEnabled(false);
        txtRelacionamentos.setEnabled(false);
        txtMultiplicidade.setEnabled(false);
        cbMultiplicidade.setEnabled(false);

        cbModificadores.setEnabled(true);
        txtTipoAtributo.setEnabled(true);
        txtNomeAtributo.setEnabled(true);
        btnAdicionarAtributo.setEnabled(true);
        btnNovaClasse.setEnabled(true);

    }//GEN-LAST:event_bntAdicionarClasseActionPerformed

    private void txtTipoAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoAtributoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoAtributoActionPerformed

    private void txtPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacoteActionPerformed

    private void btnAdicionarAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAtributoActionPerformed
        Atributo atributo = new Atributo();

        atributo.setModificador(cbModificadores.getSelectedItem().toString());
        atributo.setNome(txtNomeAtributo.getText());
        atributo.setTipo(txtTipoAtributo.getText());

        if (!atributos.contains(atributo)) {
            atributos.add(atributo);
        }

        txtNomeAtributo.setText("");
        txtTipoAtributo.setText("");
    }//GEN-LAST:event_btnAdicionarAtributoActionPerformed

    private void txtNomeAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAtributoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAtributoActionPerformed

    private void btnNovaClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaClasseActionPerformed
        Classe classe = new Classe();
        List<Atributo> atributoss = new ArrayList<>(atributos);

        classe.setNomeClasse(txtClasse.getText());
        classe.setNomePacote(txtPacote.getText());
        classe.setAtributo(atributoss);
        classe.setTipoRelacionamento(cbRelacionamentos.getSelectedItem().toString());
        if (!cbRelacionamentos.getSelectedItem().toString().equals("Sem Relacao")) {
            classe.setRelacionamento(txtRelacionamentos.getText());
        }
        classe.setTipoMultiplicidade(cbMultiplicidade.getSelectedItem().toString());
        if (!cbMultiplicidade.getSelectedItem().toString().equals("Sem Relacao")) {
            classe.setMultiplicidade(txtMultiplicidade.getText());
        }

        System.out.println(classe);

        ClasseRepositorio.adicionarClasse(classe);

        atributos.clear();

        System.out.println(classe.getAtributo());

        cbRelacionamentos.setEnabled(true);
        cbMultiplicidade.setEnabled(true);
        txtRelacionamentos.setEnabled(true);
        txtMultiplicidade.setEnabled(true);
        bntAdicionarClasse.setEnabled(true);
        txtClasse.setEnabled(true);
        txtPacote.setEnabled(true);

        cbModificadores.setEnabled(false);
        txtTipoAtributo.setEnabled(false);
        txtNomeAtributo.setEnabled(false);
        btnAdicionarAtributo.setEnabled(false);
        btnNovaClasse.setEnabled(false);
    }//GEN-LAST:event_btnNovaClasseActionPerformed

    private void btnAbrirProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirProjetoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Procurar Arquivo");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Json", "json");

        fileChooser.setFileFilter(filter);

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String conteudo = ArquivoUtils.leitura(fileChooser.getSelectedFile().getPath());
            Classe teste = (Classe) GsonUtils.xmlToObjeto(conteudo, Classe.class);
            txtRespostaClasse.setText(teste.classeToUml());
        }
    }//GEN-LAST:event_btnAbrirProjetoActionPerformed

    private void btnMostrarClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarClassesActionPerformed
        String resposta = ClasseRepositorio.classeToUml();
        txtRespostaClasse.setText(resposta);
    }//GEN-LAST:event_btnMostrarClassesActionPerformed

    private void bntSalvarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarProjetoActionPerformed
        String json = "[";
        for (Classe classe : ClasseRepositorio.getClasses()) {
            json += GsonUtils.objetoToXML(classe);
            json += ",";

        }
        json = json.substring(0, json.length() - 1);
        json += "]";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecionar Diretorio");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        String diretorio = "";
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            diretorio = fileChooser.getSelectedFile().getPath();
        }
        diretorio += "\\arquivos\\";
        File file = new File(diretorio);

        file.mkdirs();
        final String nomeArquivo = "ProjetoJSON.json";

        boolean b = ArquivoUtils.salvar(diretorio, nomeArquivo, json);
        if (b) {
            System.out.println("Arquivo criado com sucesso!");
        } else {
            System.out.println("Problemas ao criar o arquivo!");
        }


    }//GEN-LAST:event_bntSalvarProjetoActionPerformed

    private void btnSalvarEscolhidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEscolhidoActionPerformed
        String json = "";

        for (Classe classe : ClasseRepositorio.getClasses()) {
            if (classe.getNomeClasse().equals(txtSalvar.getText())) {
                System.out.println(txtSalvar.getText());
                json = GsonUtils.objetoToXML(classe);

                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setDialogTitle("Selecionar Diretorio");
                fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

                String diretorio = "";
                if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                    diretorio = fileChooser.getSelectedFile().getPath();
                }
                diretorio += "\\arquivos\\";
                File file = new File(diretorio);

                file.mkdirs();
                final String nomeArquivo = classe.getNomeClasse() + ".json";

                boolean b = ArquivoUtils.salvar(diretorio, nomeArquivo, json);
                if (b) {
                    System.out.println("Arquivo criado com sucesso!");
                } else {
                    System.out.println("Problemas ao criar o arquivo!");
                }
            }

        }
    }//GEN-LAST:event_btnSalvarEscolhidoActionPerformed

    private void btnSalvarUmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUmlActionPerformed
        String resposta = ClasseRepositorio.classeToUml();

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecionar Diretorio");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        String diretorio = "";
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            diretorio = fileChooser.getSelectedFile().getPath();
        }
        diretorio += "\\arquivos\\";
        File file = new File(diretorio);

        file.mkdirs();
        final String nomeArquivo = "UML.puml";

        boolean b = ArquivoUtils.salvar(diretorio, nomeArquivo, resposta);
        if (b) {
            System.out.println("Arquivo criado com sucesso!");
        } else {
            System.out.println("Problemas ao criar o arquivo!");
        }
    }//GEN-LAST:event_btnSalvarUmlActionPerformed

    private void cbRelacionamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRelacionamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRelacionamentosActionPerformed

    private void txtRelacionamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRelacionamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRelacionamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    private void setMetalLookAndFeel() {
        final String lookAndFeel = "javax.swing.plaf.metal.MetalLookAndFeel";

        try {
            // Set cross-platform Java L&F (also called "Metal")
            UIManager.setLookAndFeel(lookAndFeel);
        } catch (UnsupportedLookAndFeelException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        } catch (InstantiationException e) {
            System.out.println(e.getMessage());
        } catch (IllegalAccessException e) {
            System.out.println(e.getMessage());
        }
        SwingUtilities.updateComponentTreeUI(this);
    }

    private void centralizaFrameToScreem() {
        Dimension screenSize
                = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(
                (screenSize.width - this.getWidth()) / 2,
                (screenSize.height - this.getHeight()) / 2
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdicionarClasse;
    private javax.swing.JButton bntSalvarProjeto;
    private javax.swing.JButton btnAbrirProjeto;
    private javax.swing.JButton btnAdicionarAtributo;
    private javax.swing.JButton btnMostrarClasses;
    private javax.swing.JButton btnNovaClasse;
    private javax.swing.JButton btnSalvarEscolhido;
    private javax.swing.JButton btnSalvarUml;
    private javax.swing.JComboBox<String> cbModificadores;
    private javax.swing.JComboBox<String> cbMultiplicidade;
    private javax.swing.JComboBox<String> cbRelacionamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtClasse;
    private javax.swing.JTextField txtMultiplicidade;
    private javax.swing.JTextField txtNomeAtributo;
    private javax.swing.JTextField txtPacote;
    private javax.swing.JTextField txtRelacionamentos;
    private javax.swing.JTextArea txtRespostaClasse;
    private javax.swing.JTextField txtSalvar;
    private javax.swing.JTextField txtTipoAtributo;
    // End of variables declaration//GEN-END:variables
}
